# Generated by Django 4.1.13 on 2024-05-08 14:24

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('genNombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=9)),
                ('titulo', models.CharField(max_length=50)),
                ('protagonista', models.CharField(max_length=50)),
                ('duracion', models.IntegerField()),
                ('resumen', models.CharField(max_length=2000)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('pelGenero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appMovies.genero')),
            ],
        ),
    ]
